### ISSUE TITLE
{{{ yield }}} Do not show

### ISSUE THREAD

**Issue by fujihiko** [ressourcenmangel/fractal-pug-adapter#2]
Hello,
fractal-pug-adapter It's amazing

If you use _peview.hbs with fractal,  {{{yield}}} will not be displayed.

Is there a solution?

---------------------------------
─ components
    ├── 01-globalnavi
    ├── 02-header
    ├── 03-button
    ├── 04-footer
    └── _preview.hbs
─ doc
    └── index.md
---------------------------------

**Comment by gglnx** [comment]
Hello, thanks :)

`{{{ yield }}}` is the handlebars way. Your preview template must be in Pug too (currently no way for multiple template languages inside Fractal). So, for example:

```pug
.preview
  != yield
```

Important is `!= yield`. This renders the raw content.

I hope it helps :)

**Comment by fujihiko** [comment]
Hello !! gglnx.

Thank you for telling me.

I could display it without problems.

Thank you very much :smile:

**Comment by fujihiko** [comment]
I am sorry many times gglnx.

If you knew, please tell me.
I load style with _preview.pug,
I do not know how to describe it with pug.

`<link media="all" rel="stylesheet" href="{{ path '/css/pc.css'}}">`

Is there a solution?

**Comment by gglnx** [comment]
That's no problem. The project is currently missing documentation, so ask everything you want.

The pug adapter has also a path helper. You can use it this way:

```pug
link(media='all', rel='stylesheet', href=path('/css/pc.css'))
```

**Comment by fujihiko** [comment]
Hi,gglnx
Sorry for replying so late.

I solved it successfully with the description you taught.

It was very helpful. Thank you very much. :smile::smile:
